### ISSUE TITLE
Add mypy to pre-commit hooks

### ISSUE THREAD

**Issue by Mews** [indrajithi/tiny-web-crawler#20]
I noticed this when working in #19 
Type checking with mypy is done in the ci, but its not included in the pre-commit hooks.
Should probably be added.

**Comment by indrajithi** [comment]
Good idea. I was also trying to make the test run before pushing. Could you add that also in this issue.

**Comment by Mews** [comment]
Yeah I can submit a pr for this if you want :)

**Comment by indrajithi** [comment]
@Mews Were you able to see if you can make the test run before we push? I did try for sometime, couldn't get it working.

**Comment by Mews** [comment]
I tried doing a few commits on my machine and the tests ran 👍 
Aren't they running on your machine?

**Comment by indrajithi** [comment]
For commits the test runs in my machine as well. That is not what I was saying. Since running test will be expensive, I was thinking to add that hook before we push. When we commit it should not run tests. Sometimes we might commit quite frequently and it might become a pain to run the test every time. It would be best if we can run the tests automatically before push.

**Comment by Mews** [comment]
Yes, you can do that.
I changed the `.pre-commit-config.yaml` on the pr for it to run on push, but, for it to work, you also have to install the push hook through this command: `pre-commit install --hook-type pre-push`
